### ISSUE TITLE
html to docx image not parsing

### ISSUE THREAD

**Issue by htmls** [PHPOffice/PHPWord#1288]
Hello.

I'm using 
\PhpOffice\PhpWord\Shared\Html::addHtml($section, $html, true, false);
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');

My $html contains several images like `<img src="https://path_to_image">`
$objWriter->save($file_name . '.docx'); returns a blank DOCX.

Without <img > it works properly.
What's wrong?
```

### Context

* PHP version: 7.0.1
* PHPWord version: 0.13

**Comment by troosan** [comment]
There was indeed a problem with the parsing of images in version 0.13
This has normally been fixed in 0.14, can you try it out please?

**Comment by htmls** [comment]
How can I do it?
I've used {
    "require": {
       "phpoffice/phpword": "v0.14.*"
    }
}
It installed 0.13.0

**Comment by troosan** [comment]
@htmls don't get fooled by the VERSION file, it did not get updated when 0.14 was released. You should have 0.14 installed. You can run `composer show` to list all your dependencies and their version.

**Comment by htmls** [comment]
sure.
pclzip/pclzip              2.8.2   A PHP library that offers compression an...
phpoffice/common           0.2.7   PHPOffice Common
phpoffice/phpword          v0.14.0 PHPWord - A pure PHP library for reading...
zendframework/zend-escaper 2.5.1
zendframework/zend-stdlib  2.5.1

But I'm still getting a blank docx when using html with <img >

**Comment by troosan** [comment]
Can you post the html you are parsing?
